// <auto-generated />
namespace Library_Managment_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MakeMembershipTypeIdNullableInUserClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeMembershipTypeIdNullableInUserClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202007292324037_MakeMembershipTypeIdNullableInUserClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
